version: '2.1'
services:
  homeassistant:
    image: homeassistant/home-assistant:0.95.4
    container_name: home-assistant
    restart: always
    network_mode: 'host'
    ports:
      - '8123:8123'
      - '8943:8943'
    volumes:
      - '/home/jamie/smith-home-assistant:/config'
    devices:
      - '/dev/ttyACM0'
    environment:
      - 'TZ=America/New_York'
    logging:
      options:
        max-size: 25m
