blueprint:
  name: Minoston S2 Remote Control Switch
  description: Create automations for the Minoston S2
  domain: automation

  input:
    minoston_s2_device:
      name: Minoston S2 Remote
      description: A Minoston S2 Remote device.
      selector:
        device:
          integration: zwave_js
          manufacturer: Minoston
          model: MR40Z

    button_1_pressed:
      name: Button 1 Pressed
      description: Actions to run when button 1 is pressed.
      default: []
      selector:
        action:

    button_1_pressed_2x:
      name: Button 1 Pressed Twice
      description: Actions to run when button 1 is pressed twice
      default: []
      selector:
        action:

    button_1_pressed_3x:
      name: Button 1 Pressed Thrice
      description: Actions to run when button 1 is pressed thrice
      default: []
      selector:
        action:

    button_2_pressed:
      name: Button 2 Pressed
      description: Actions to run when button 2 is pressed.
      default: []
      selector:
        action:

    button_2_pressed_2x:
      name: Button 2 Pressed Twice
      description: Actions to run when button 2 is pressed twice
      default: []
      selector:
        action:

    button_2_pressed_3x:
      name: Button 2 Pressed Thrice
      description: Actions to run when button 2 is pressed thrice
      default: []
      selector:
        action:

    button_3_pressed:
      name: Button 3 Pressed
      description: Actions to run when button 3 is pressed.
      default: []
      selector:
        action:

    button_3_pressed_2x:
      name: Button 3 Pressed Twice
      description: Actions to run when button 3 is pressed twice
      default: []
      selector:
        action:

    button_3_pressed_3x:
      name: Button 3 Pressed Thrice
      description: Actions to run when button 3 is pressed thrice
      default: []
      selector:
        action:

    button_4_pressed:
      name: Button 4 Pressed
      description: Actions to run when button 4 is pressed.
      default: []
      selector:
        action:

    button_4_pressed_2x:
      name: Button 4 Pressed Twice
      description: Actions to run when button 4 is pressed twice
      default: []
      selector:
        action:

    button_4_pressed_3x:
      name: Button 4 Pressed Thrice
      description: Actions to run when button 4 is pressed thrice
      default: []
      selector:
        action:

mode: single
max_exceeded: silent

trigger:
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input minoston_s2_device
    command_class_name: "Central Scene"

action:
  - variables:
      action_name: "{{ trigger.event.data.value }}"
      property_key: "{{ trigger.event.data.property_key }}"
  - choose:
      - conditions:   "{{ action_name == 'KeyPressed' and property_key == '001'}}"
        sequence: !input button_1_pressed
      - conditions: "{{ action_name == 'KeyPressed2x' and property_key == '001' }}"
        sequence: !input button_1_pressed_2x
      - conditions: "{{ action_name == 'KeyPressed3x' and property_key == '001' }}"
        sequence: !input button_1_pressed_3x

      - conditions:   "{{ action_name == 'KeyPressed' and property_key == '002'}}"
        sequence: !input button_2_pressed
      - conditions: "{{ action_name == 'KeyPressed2x' and property_key == '002' }}"
        sequence: !input button_2_pressed_2x
      - conditions: "{{ action_name == 'KeyPressed3x' and property_key == '002' }}"
        sequence: !input button_2_pressed_3x

      - conditions: "{{ action_name == 'KeyPressed' and property_key == '003'}}"
        sequence: !input button_3_pressed
      - conditions: "{{ action_name == 'KeyPressed2x' and property_key == '003' }}"
        sequence: !input button_3_pressed_2x
      - conditions: "{{ action_name == 'KeyPressed3x' and property_key == '003' }}"
        sequence: !input button_3_pressed_3x

      - conditions: "{{ action_name == 'KeyPressed' and property_key == '004'}}"
        sequence: !input button_4_pressed
      - conditions: "{{ action_name == 'KeyPressed2x' and property_key == '004' }}"
        sequence: !input button_4_pressed_2x
      - conditions: "{{ action_name == 'KeyPressed3x' and property_key == '004' }}"
        sequence: !input button_4_pressed_3x
