# This is the automations file
#
- id: accent_lighting_on_time
  alias: Turn On Accent Lighting around sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: script.turn_on_accent_lighting

- id: accent_lighting_off_time
  alias: Turn Off Accent Lighting
  trigger:
    platform: time
    at: "22:15:00"
  action:
    - service: script.turn_off_accent_lighting

- id: cabinet_lighting_on_switch
  alias: Turn On Cabinet Lighting
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_light
        scene_data: 3 # double-tap
        scene_id: 1   # On
    # JRS-TMP - platform: state
    # JRS-TMP   entity_id: sensor.dark_outside
    # JRS-TMP   to: 'true' 
  action:
    - service: homeassistant.turn_on
      entity_id: group.cabinet_lighting

- id: cabinet_lighting_off_switch
  alias: Turn Off Cabinet Lighting
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_light
        scene_data: 3 # double-tap
        scene_id: 2   # Off
    - platform: state
      entity_id: sensor.dark_outside
      to: 'false' 
  action:
    - service: homeassistant.turn_off
      entity_id: group.cabinet_lighting

- id: foyer_lighting_off
  alias: Turn Off Foyer Lighting
  trigger:
    platform: time
    at: "23:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.foyer_outlet_switch_2

- id: landscape_lighting_on
  alias: Turn On Landscape Lighting around sunset
  trigger:
    platform: sun
    event: sunset
    offset: "+00:15:00"
  action:
    - service: homeassistant.turn_on
      entity_id: group.landscape_lights

- id: landscape_lighting_off
  alias: Turn Off Landscape Lighting
  trigger:
    platform: time
    at: "23:59:00"
  action:
    - service: homeassistant.turn_off
      entity_id: group.landscape_lights

- id: jamie_bedtime_music
  alias: Turn on Jamies bedtime music
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_light
        scene_data: 4 # triple-tap
        scene_id: 2   # Off
    - platform: time
      at: "22:00:00"
    - platform: time
      at: "01:00:00"
  action:
    - service: script.jamie_bedtime_music
    
# Bulk one for quad testing
#
- id: bulk_quad_detector
  alias: Bulk Quad Detector
#  hide_entity: true
  trigger:
    platform: event
    event_type: zwave.scene_activated
  action:
    - service: shell_command.quad_button_handler
      data_template:
        scene_id: "{{ trigger.event.data.scene_id }}"
        scene_data: "{{ trigger.event.data.scene_data }}"
        entity_id: "{{ trigger.event.data.entity_id }}"

- id: turn_off_office
  alias: Turn Off the Office Receiver
  trigger:
    platform: time
    at: "20:00:00"
  action:
    - service: script.turn_off_office
      
